<a href="https://colab.research.google.com/github/allansdefreitas/unsupervised-learning/blob/main/FUZZY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd

In [60]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [61]:
"""
I. Considere os dados "Image Segmentation" do site uci machine learning
repository (https://archive.ics.uci.edu/ml/datasets/Image+Segmentation).


"""

'\nI. Considere os dados "Image Segmentation" do site uci machine learning\nrepository (https://archive.ics.uci.edu/ml/datasets/Image+Segmentation).\n\n\n'

In [62]:
PATH = 'https://raw.githubusercontent.com/allansdefreitas/unsupervised-learning/main/segmentation.data'

In [63]:

dataset_original = pd.read_csv(PATH, sep=',').reset_index(drop=True)
dataset_original

REGION-CENTROID-COL  REGION-CENTROID-ROW  REGION-PIXEL-COUNT  \
0                  140.0                125.0                   9   
1                  188.0                133.0                   9   
2                  105.0                139.0                   9   
3                   34.0                137.0                   9   
4                   39.0                111.0                   9   
..                   ...                  ...                 ...   
205                 36.0                243.0                   9   
206                186.0                218.0                   9   
207                197.0                236.0                   9   
208                208.0                240.0                   9   
209                223.0                185.0                   9   

     SHORT-LINE-DENSITY-5  SHORT-LINE-DENSITY-2  VEDGE-MEAN  VEDGE-SD  \
0                0.000000                   0.0    0.277778  0.062963   
1                0.000000                   0.0    0.333333  0.266667   
2                0.000000                   0.0    0.277778  0.107407   
3                0.000000                   0.0    0.500000  0.166667   
4                0.000000                   0.0    0.722222  0.374074   
..                    ...                   ...         ...       ...   
205              0.111111                   0.0    1.888889  1.851851   
206              0.000000                   0.0    1.166667  0.744444   
207              0.000000                   0.0    2.444444  6.829628   
208              0.111111                   0.0    1.055556  0.862963   
209              0.000000                   0.0    0.500000  0.349603   

     HEDGE-MEAN  HEDGE-SD  INTENSITY-MEAN  RAWRED-MEAN  RAWBLUE-MEAN  \
0      0.666667  0.311111        6.185185     7.333334      7.666666   
1      0.500000  0.077778        6.666666     8.333334      7.777778   
2      0.833333  0.522222        6.111111     7.555555      7.222222   
3      1.111111  0.474074        5.851852     7.777778      6.444445   
4      0.888889  0.429629        6.037037     7.000000      7.666666   
..          ...       ...             ...          ...           ...   
205    2.000000  0.711110       13.333333     9.888889     12.111111   
206    1.166667  0.655555       13.703704    10.666667     12.666667   
207    3.333333  7.599998       16.074074    13.111111     16.666668   
208    2.444444  5.007407       14.148149    10.888889     13.000000   
209    2.388889  2.080776       12.962963    11.555555      9.777778   

     RAWGREEN-MEAN  EXRED-MEAN  EXBLUE-MEAN  EXGREEN-MEAN  VALUE-MEAN  \
0         3.555556    3.444444     4.444445     -7.888889    7.777778   
1         3.888889    5.000000     3.333333     -8.333333    8.444445   
2         3.555556    4.333334     3.333333     -7.666666    7.555555   
3         3.333333    5.777778     1.777778     -7.555555    7.777778   
4         3.444444    2.888889     4.888889     -7.777778    7.888889   
..             ...         ...          ...           ...         ...   
205      18.000000  -10.333333    -3.666667     14.000000   18.000000   
206      17.777779   -9.111111    -3.111111     12.222222   17.777779   
207      18.444445   -8.888889     1.777778      7.111111   18.555555   
208      18.555555   -9.777778    -3.444444     13.222222   18.555555   
209      17.555555   -4.222222    -9.555555     13.777778   17.555555   

     SATURATION-MEAN  HUE-MEAN  
0           0.545635 -1.121818  
1           0.538580 -0.924817  
2           0.532628 -0.965946  
3           0.573633 -0.744272  
4           0.562919 -1.175773  
..               ...       ...  
205         0.452229  2.368311  
206         0.401347  2.382684  
207         0.292729  2.789800  
208         0.421621  2.392487  
209         0.445418  1.838850  

[210 rows x 19 columns]

In [64]:
"""
Considere 3 datasets: 

o primeiro considerando as variáveis 4 a 9 (shape)

"""

dataset_1_shape = dataset_original.iloc[:,3:9]
dataset_1_shape

SHORT-LINE-DENSITY-5  SHORT-LINE-DENSITY-2  VEDGE-MEAN  VEDGE-SD  \
0                0.000000                   0.0    0.277778  0.062963   
1                0.000000                   0.0    0.333333  0.266667   
2                0.000000                   0.0    0.277778  0.107407   
3                0.000000                   0.0    0.500000  0.166667   
4                0.000000                   0.0    0.722222  0.374074   
..                    ...                   ...         ...       ...   
205              0.111111                   0.0    1.888889  1.851851   
206              0.000000                   0.0    1.166667  0.744444   
207              0.000000                   0.0    2.444444  6.829628   
208              0.111111                   0.0    1.055556  0.862963   
209              0.000000                   0.0    0.500000  0.349603   

     HEDGE-MEAN  HEDGE-SD  
0      0.666667  0.311111  
1      0.500000  0.077778  
2      0.833333  0.522222  
3      1.111111  0.474074  
4      0.888889  0.429629  
..          ...       ...  
205    2.000000  0.711110  
206    1.166667  0.655555  
207    3.333333  7.599998  
208    2.444444  5.007407  
209    2.388889  2.080776  

[210 rows x 6 columns]

In [65]:
"""

o segundo considerando as variaveis 10 a 19 (rgb), 

"""

dataset_2_rgb = dataset_original.iloc[:,9:19]
dataset_2_rgb

INTENSITY-MEAN  RAWRED-MEAN  RAWBLUE-MEAN  RAWGREEN-MEAN  EXRED-MEAN  \
0          6.185185     7.333334      7.666666       3.555556    3.444444   
1          6.666666     8.333334      7.777778       3.888889    5.000000   
2          6.111111     7.555555      7.222222       3.555556    4.333334   
3          5.851852     7.777778      6.444445       3.333333    5.777778   
4          6.037037     7.000000      7.666666       3.444444    2.888889   
..              ...          ...           ...            ...         ...   
205       13.333333     9.888889     12.111111      18.000000  -10.333333   
206       13.703704    10.666667     12.666667      17.777779   -9.111111   
207       16.074074    13.111111     16.666668      18.444445   -8.888889   
208       14.148149    10.888889     13.000000      18.555555   -9.777778   
209       12.962963    11.555555      9.777778      17.555555   -4.222222   

     EXBLUE-MEAN  EXGREEN-MEAN  VALUE-MEAN  SATURATION-MEAN  HUE-MEAN  
0       4.444445     -7.888889    7.777778         0.545635 -1.121818  
1       3.333333     -8.333333    8.444445         0.538580 -0.924817  
2       3.333333     -7.666666    7.555555         0.532628 -0.965946  
3       1.777778     -7.555555    7.777778         0.573633 -0.744272  
4       4.888889     -7.777778    7.888889         0.562919 -1.175773  
..           ...           ...         ...              ...       ...  
205    -3.666667     14.000000   18.000000         0.452229  2.368311  
206    -3.111111     12.222222   17.777779         0.401347  2.382684  
207     1.777778      7.111111   18.555555         0.292729  2.789800  
208    -3.444444     13.222222   18.555555         0.421621  2.392487  
209    -9.555555     13.777778   17.555555         0.445418  1.838850  

[210 rows x 10 columns]

In [66]:
"""
o terceiro considerando as variaveis 4 a 19 (shape + rgb)

"""

dataset_shape_rgb = dataset_original.iloc[:,3:19]
dataset_shape_rgb

SHORT-LINE-DENSITY-5  SHORT-LINE-DENSITY-2  VEDGE-MEAN  VEDGE-SD  \
0                0.000000                   0.0    0.277778  0.062963   
1                0.000000                   0.0    0.333333  0.266667   
2                0.000000                   0.0    0.277778  0.107407   
3                0.000000                   0.0    0.500000  0.166667   
4                0.000000                   0.0    0.722222  0.374074   
..                    ...                   ...         ...       ...   
205              0.111111                   0.0    1.888889  1.851851   
206              0.000000                   0.0    1.166667  0.744444   
207              0.000000                   0.0    2.444444  6.829628   
208              0.111111                   0.0    1.055556  0.862963   
209              0.000000                   0.0    0.500000  0.349603   

     HEDGE-MEAN  HEDGE-SD  INTENSITY-MEAN  RAWRED-MEAN  RAWBLUE-MEAN  \
0      0.666667  0.311111        6.185185     7.333334      7.666666   
1      0.500000  0.077778        6.666666     8.333334      7.777778   
2      0.833333  0.522222        6.111111     7.555555      7.222222   
3      1.111111  0.474074        5.851852     7.777778      6.444445   
4      0.888889  0.429629        6.037037     7.000000      7.666666   
..          ...       ...             ...          ...           ...   
205    2.000000  0.711110       13.333333     9.888889     12.111111   
206    1.166667  0.655555       13.703704    10.666667     12.666667   
207    3.333333  7.599998       16.074074    13.111111     16.666668   
208    2.444444  5.007407       14.148149    10.888889     13.000000   
209    2.388889  2.080776       12.962963    11.555555      9.777778   

     RAWGREEN-MEAN  EXRED-MEAN  EXBLUE-MEAN  EXGREEN-MEAN  VALUE-MEAN  \
0         3.555556    3.444444     4.444445     -7.888889    7.777778   
1         3.888889    5.000000     3.333333     -8.333333    8.444445   
2         3.555556    4.333334     3.333333     -7.666666    7.555555   
3         3.333333    5.777778     1.777778     -7.555555    7.777778   
4         3.444444    2.888889     4.888889     -7.777778    7.888889   
..             ...         ...          ...           ...         ...   
205      18.000000  -10.333333    -3.666667     14.000000   18.000000   
206      17.777779   -9.111111    -3.111111     12.222222   17.777779   
207      18.444445   -8.888889     1.777778      7.111111   18.555555   
208      18.555555   -9.777778    -3.444444     13.222222   18.555555   
209      17.555555   -4.222222    -9.555555     13.777778   17.555555   

     SATURATION-MEAN  HUE-MEAN  
0           0.545635 -1.121818  
1           0.538580 -0.924817  
2           0.532628 -0.965946  
3           0.573633 -0.744272  
4           0.562919 -1.175773  
..               ...       ...  
205         0.452229  2.368311  
206         0.401347  2.382684  
207         0.292729  2.789800  
208         0.421621  2.392487  
209         0.445418  1.838850  

[210 rows x 16 columns]

In [67]:
"""
Em cada dataset execute o algoritmo FCM com a distância de City-Block
50 vezes para obter uma partição fuzzy em 7 grupos e selecione o melhor
resultado segundo a função objetivo.

"""

'\nEm cada dataset execute o algoritmo FCM com a distância de City-Block\n50 vezes para obter uma partição fuzzy em 7 grupos e selecione o melhor\nresultado segundo a função objetivo.\n\n'

In [68]:
!pip install -U scikit-fuzzy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [69]:
import numpy as np
import matplotlib.pyplot as plt
import skfuzzy
from sklearn.preprocessing import StandardScaler

In [70]:
scaler = StandardScaler()
X_dataset_1_shape = scaler.fit_transform(dataset_1_shape)
X_dataset_1_shape

array([[-0.28718326, -0.21160368, -0.52285631, -0.13035889, -0.40477019,
        -0.11658619],
       [-0.28718326, -0.21160368, -0.50522349, -0.12566442, -0.43958796,
        -0.11898778],
       [-0.28718326, -0.21160368, -0.52285634, -0.12933464, -0.36995247,
        -0.11441333],
       ...,
       [-0.28718326, -0.21160368,  0.16482524,  0.02558287,  0.15231385,
        -0.04156512],
       [ 3.48209707, -0.21160368, -0.27599624, -0.11192241, -0.03338084,
        -0.06824944],
       [-0.28718326, -0.21160368, -0.4523249 , -0.1237531 , -0.04498681,
        -0.09837187]])

In [125]:
R_dataset_1_shape = skfuzzy.cmeans(data = X_dataset_1_shape.T, c = 7, m = 2, error=0.005, maxiter= 1000, init=None)
R_dataset_1_shape

(array([[-0.26053939, -0.1085328 ,  0.2726398 ,  0.19002883,  2.96555155,
          0.62531204],
        [ 3.46293052, -0.1744644 , -0.12172778, -0.07605384, -0.07976713,
         -0.08096839],
        [-0.28400836, -0.2029257 , -0.0165253 , -0.07565774, -0.06129425,
         -0.08795358],
        [-0.27307623, -0.1712507 ,  0.73128917,  0.02402577,  0.26245074,
         -0.01514368],
        [-0.25440411,  3.42374871,  6.13868561,  0.63485859,  5.00379301,
          0.5068252 ],
        [-0.13268318,  3.73503608,  0.26461421,  0.03331486,  0.48842351,
          0.04402712],
        [-0.28592801, -0.20822761, -0.37056312, -0.1165957 , -0.36399028,
         -0.10977228]]),
 array([[1.82974741e-03, 1.73061492e-03, 1.74209658e-03, ...,
         7.44866674e-03, 1.20994545e-03, 6.39767745e-03],
        [1.61541773e-03, 1.55204773e-03, 1.51147548e-03, ...,
         4.40708378e-03, 9.91552323e-01, 4.61282538e-03],
        [6.12244377e-02, 5.77574256e-02, 6.08907680e-02, ...,
         6.882829

In [121]:
len(R_dataset_1_shape)

7

In [127]:
U = R_dataset_1_shape[1]
U

array([[1.82974741e-03, 1.73061492e-03, 1.74209658e-03, ...,
        7.44866674e-03, 1.20994545e-03, 6.39767745e-03],
       [1.61541773e-03, 1.55204773e-03, 1.51147548e-03, ...,
        4.40708378e-03, 9.91552323e-01, 4.61282538e-03],
       [6.12244377e-02, 5.77574256e-02, 6.08907680e-02, ...,
        6.88282926e-01, 2.02752872e-03, 3.39396542e-01],
       ...,
       [2.63696821e-04, 2.53123021e-04, 2.47426151e-04, ...,
        8.56706156e-04, 3.05531206e-04, 7.87093707e-04],
       [1.35661091e-03, 1.30159024e-03, 1.27202270e-03, ...,
        3.98191222e-03, 9.88317843e-04, 3.97728787e-03],
       [9.22435700e-01, 9.26580631e-01, 9.23561914e-01, ...,
        1.08349926e-01, 2.01838335e-03, 6.01973060e-01]])

In [154]:
U.shape

(7, 210)

In [167]:
U[6][0]

0.9224356996345915

In [172]:
sum = 0
for i in range(7):
  sum +=  U[i][0]

print(sum)

1.0


In [93]:
R_dataset_1_shape = np.asarray(R_dataset_1_shape)
R_dataset_1_shape.shape, type(R_dataset_1_shape)

((7,), numpy.ndarray)

In [118]:
R_dataset_1_shape[0][6][0]

3.4629308014148563

In [119]:
sum = 0
for i in range(5):
  sum = R_dataset_1_shape[0][i][0]

print(sum)

-0.13268243349744513


In [72]:
import numpy as np


def initialize_membership_matrix(n_samples, n_clusters):
    """
    Initializes the membership matrix for Fuzzy C-Means.

    Parameters:
        n_samples (int): Number of data points.
        n_clusters (int): Number of clusters.

    Returns:
        numpy.ndarray: Initial membership matrix.
    """
    membership_matrix = np.random.rand(n_samples, n_clusters)
    membership_matrix /= np.sum(membership_matrix, axis=1, keepdims=True)
    return membership_matrix


def update_membership_matrix(data, centroids, m, distance_metric):
    """
    Updates the membership matrix for Fuzzy C-Means.

    Parameters:
        data (numpy.ndarray): Input data points.
        centroids (numpy.ndarray): Current centroid positions.
        m (float): Fuzziness parameter.
        distance_metric (str): Distance metric to use ('cityblock' or 'euclidean').

    Returns:
        numpy.ndarray: Updated membership matrix.
    """
    n_samples, n_clusters = data.shape[0], centroids.shape[0]
    membership_matrix = np.zeros((n_samples, n_clusters))

    for i in range(n_samples):
        for j in range(n_clusters):
            if distance_metric == 'cityblock':
                dist = np.sum(np.abs(data[i] - centroids[j]))
            elif distance_metric == 'euclidean':
                dist = np.linalg.norm(data[i] - centroids[j])
            else:
                raise ValueError("Invalid distance metric.")

            membership_matrix[i, j] = 1 / np.sum((dist / np.abs(data[i] - centroids)) ** (2 / (m - 1)))

    membership_matrix /= np.sum(membership_matrix, axis=1, keepdims=True)
    return membership_matrix


def update_centroids(data, membership_matrix, m):
    """
    Updates the centroids for Fuzzy C-Means.

    Parameters:
        data (numpy.ndarray): Input data points.
        membership_matrix (numpy.ndarray): Current membership matrix.
        m (float): Fuzziness parameter.

    Returns:
        numpy.ndarray: Updated centroid positions.
    """
    n_clusters, n_features = membership_matrix.shape[1], data.shape[1]
    centroids = np.zeros((n_clusters, n_features))

    for j in range(n_clusters):
        membership_power = membership_matrix[:, j] ** m
        centroids[j] = np.sum(membership_power.reshape(-1, 1) * data, axis=0) / np.sum(membership_power)

    return centroids


def fuzzy_cmeans(data, n_clusters, m, distance_metric='cityblock', max_iter=100, tolerance=1e-4):
    """
    Fuzzy C-Means clustering algorithm.

    Parameters:
        data (numpy.ndarray): Input data points.
        n_clusters (int): Number of clusters.
        m (float): Fuzziness parameter (> 1).
        distance_metric (str): Distance metric to use ('cityblock' or 'euclidean').
        max_iter (int): Maximum number of iterations.
        tolerance (float): Convergence tolerance.

    Returns:
        numpy.ndarray: Final centroid positions.
        numpy.ndarray: Membership matrix.
        int: Number of iterations performed.
    """
    n_samples, n_features = data.shape
    membership_matrix = initialize_membership_matrix(n_samples, n_clusters)
    centroids = np.zeros((n_clusters, n_features))

    for iteration in range(max_iter):
        prev_centroids = centroids.copy()

        centroids = update_centroids(data, membership_matrix, m)
        membership_matrix = update_membership_matrix(data, centroids, m, distance_metric)

        if np.linalg.norm(centroids - prev_centroids) < tolerance:
            break

    return centroids, membership_matrix, iteration+1


In [73]:
X_dataset_1_shape

array([[-0.28718326, -0.21160368, -0.52285631, -0.13035889, -0.40477019,
        -0.11658619],
       [-0.28718326, -0.21160368, -0.50522349, -0.12566442, -0.43958796,
        -0.11898778],
       [-0.28718326, -0.21160368, -0.52285634, -0.12933464, -0.36995247,
        -0.11441333],
       ...,
       [-0.28718326, -0.21160368,  0.16482524,  0.02558287,  0.15231385,
        -0.04156512],
       [ 3.48209707, -0.21160368, -0.27599624, -0.11192241, -0.03338084,
        -0.06824944],
       [-0.28718326, -0.21160368, -0.4523249 , -0.1237531 , -0.04498681,
        -0.09837187]])

In [76]:
X_array_dataset_1_shape = np.asarray(X_dataset_1_shape)
X_array_dataset_1_shape

array([[-0.28718326, -0.21160368, -0.52285631, -0.13035889, -0.40477019,
        -0.11658619],
       [-0.28718326, -0.21160368, -0.50522349, -0.12566442, -0.43958796,
        -0.11898778],
       [-0.28718326, -0.21160368, -0.52285634, -0.12933464, -0.36995247,
        -0.11441333],
       ...,
       [-0.28718326, -0.21160368,  0.16482524,  0.02558287,  0.15231385,
        -0.04156512],
       [ 3.48209707, -0.21160368, -0.27599624, -0.11192241, -0.03338084,
        -0.06824944],
       [-0.28718326, -0.21160368, -0.4523249 , -0.1237531 , -0.04498681,
        -0.09837187]])

In [79]:
# Example usage

#data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
data = X_array_dataset_1_shape
n_clusters = 7
m = 2
distance_metric = 'cityblock'

centroids, membership_matrix, iterations = fuzzy_cmeans(data, n_clusters, m, distance_metric)
print("Centroids:")
print(centroids)
print("Membership matrix:")
print(membership_matrix)
print("Iterations:", iterations)

Centroids:
[[-0.28036309 -0.19372274  3.25813479  5.9283029   1.36509818  1.95829855]
 [ 3.4522129  -0.10650163 -0.120604   -0.09706789 -0.09119112 -0.10009407]
 [-0.05781558  4.00219207  0.21516951 -0.06230254  0.43979693 -0.04699883]
 [-0.28636451 -0.20949622 -0.2080037  -0.10549249 -0.2519734  -0.10788411]
 [-0.28689201  3.49132886  7.1288204  13.07012298  8.79685184 14.1456492 ]
 [-0.27582005 -0.173778    0.21131031 -0.03129693  1.83764649  0.45798971]
 [-0.27626834  3.43001995  5.87426344  0.23207112  4.97557146  0.11882226]]
Membership matrix:
[[1.30075161e-03 1.15024306e-02 6.43534729e-03 ... 1.06018621e-04
  1.78627272e-02 9.51618332e-04]
 [1.37296929e-03 1.20892070e-02 6.77462570e-03 ... 1.12078497e-04
  1.87442356e-02 1.00476758e-03]
 [1.12376677e-03 1.00473509e-02 5.59777957e-03 ... 9.12304784e-05
  1.56671279e-02 8.21476737e-04]
 ...
 [5.01693710e-03 3.61933429e-02 3.16013197e-02 ... 3.46587748e-04
  1.37420047e-01 3.54551688e-03]
 [5.45253236e-04 9.84510293e-01 1.98745196e

In [81]:
membership_matrix.shape

(210, 7)

In [86]:
sum = 0
for i in range(210):
  sum = membership_matrix[i][0]

print(sum)

0.001266277743450831


In [ ]:
print()