<a href="https://colab.research.google.com/github/allansdefreitas/unsupervised-learning/blob/main/FUZZY2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install scikit-fuzzy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import skfuzzy
from sklearn.preprocessing import StandardScaler
from numpy import savetxt
from numpy import loadtxt
from sklearn.metrics import adjusted_rand_score
from sklearn import metrics
from sklearn import preprocessing

def preprocess_dataset(dataframe):
    
    #pre-processing of dataset
    scaler = StandardScaler()
    data = scaler.fit_transform(dataframe.values)
    
    return data


def initialize_membership_matrix(n_samples, n_clusters):
    """
    Initializes the membership matrix for Fuzzy C-Means.

    Parameters:
        n_samples (int): Number of data points.
        n_clusters (int): Number of clusters.

    Returns:
        numpy.ndarray: Initial membership matrix.
    """
    membership_matrix = np.random.rand(n_samples, n_clusters)
    membership_matrix /= np.sum(membership_matrix, axis=1, keepdims=True)
    return membership_matrix


def update_membership_matrix(data, centroids, m, distance_metric):
    """
    Updates the membership matrix for Fuzzy C-Means.

    Parameters:
        data (numpy.ndarray): Input data points.
        centroids (numpy.ndarray): Current centroid positions.
        m (float): Fuzziness parameter.
        distance_metric (str): Distance metric to use ('cityblock' or 'euclidean').

    Returns:
        numpy.ndarray: Updated membership matrix.
    """
    n_samples, n_clusters = data.shape[0], centroids.shape[0]
    membership_matrix = np.zeros((n_samples, n_clusters))

    for i in range(n_samples):
        for j in range(n_clusters):
            if distance_metric == 'cityblock':
                dist = np.sum(np.abs(data[i] - centroids[j]))
            elif distance_metric == 'euclidean':
                dist = np.linalg.norm(data[i] - centroids[j])
            else:
                raise ValueError("Invalid distance metric.")

            membership_matrix[i, j] = 1 / np.sum((dist / np.abs(data[i] - centroids)) ** (2 / (m - 1)))

    membership_matrix /= np.sum(membership_matrix, axis=1, keepdims=True)
    return membership_matrix


def update_centroids(data, membership_matrix, m):
    """
    Updates the centroids for Fuzzy C-Means.

    Parameters:
        data (numpy.ndarray): Input data points.
        membership_matrix (numpy.ndarray): Current membership matrix.
        m (float): Fuzziness parameter.

    Returns:
        numpy.ndarray: Updated centroid positions.
    """
    n_clusters, n_features = membership_matrix.shape[1], data.shape[1]
    centroids = np.zeros((n_clusters, n_features))

    for j in range(n_clusters):
        membership_power = membership_matrix[:, j] ** m
        centroids[j] = np.sum(membership_power.reshape(-1, 1) * data, axis=0) / np.sum(membership_power)

    return centroids

def fuzzy_cmeans(data, n_clusters, m, distance_metric='cityblock', max_iter=100, tolerance=1e-4):
    """
    Fuzzy C-Means clustering algorithm.

    Parameters:
        data (numpy.ndarray): Input data points.
        n_clusters (int): Number of clusters.
        m (float): Fuzziness parameter (> 1).
        distance_metric (str): Distance metric to use ('cityblock' or 'euclidean').
        max_iter (int): Maximum number of iterations.
        tolerance (float): Convergence tolerance.

    Returns:
        numpy.ndarray: Final centroid positions.
        numpy.ndarray: Membership matrix.
        int: Number of iterations performed.
    """
    n_samples, n_features = data.shape
    membership_matrix = initialize_membership_matrix(n_samples, n_clusters)
    centroids = np.zeros((n_clusters, n_features))

    for iteration in range(max_iter):
        prev_centroids = centroids.copy()

        centroids = update_centroids(data, membership_matrix, m)
        membership_matrix = update_membership_matrix(data, centroids, m, distance_metric)

        if np.linalg.norm(centroids - prev_centroids) < tolerance:
            break

    return centroids, membership_matrix, iteration+1



def calculate_objective(data, centroids, membership_matrix, m, distance_metric):
    """
    Calculates the objective function value for Fuzzy C-Means.

    Parameters:
        data (numpy.ndarray): Input data points.
        centroids (numpy.ndarray): Current centroid positions.
        membership_matrix (numpy.ndarray): Current membership matrix.
        m (float): Fuzziness parameter.
        distance_metric (str): Distance metric to use ('cityblock' or 'euclidean').

    Returns:
        float: Objective function value.
    """
    objective = 0
    n_samples, n_clusters = data.shape[0], centroids.shape[0]

    for i in range(n_samples):
        for j in range(n_clusters):
            if distance_metric == 'cityblock':
                dist = np.sum(np.abs(data[i] - centroids[j]))
            elif distance_metric == 'euclidean':
                dist = np.linalg.norm(data[i] - centroids[j])
            else:
                raise ValueError("Invalid distance metric.")

            objective += (membership_matrix[i, j] ** m) * (dist ** 2)

    return objective

#Modified partition coefficient e partition entropy --------------################


#close to 1 values are better
#A value of 0 indicates complete fuzziness, where data points have equal membership to all clusters
#A value of 1 indicates crisp or hard clustering, where data points have membership to only one cluster.
def calculate_mpc(membership_matrix):
    """
    Calculates the Modified Partition Coefficient (MPC) for Fuzzy C-Means clustering.

    Parameters:
        membership_matrix (numpy.ndarray): Membership matrix of shape (n_samples, n_clusters).

    Returns:
        float: Modified Partition Coefficient value.
    """
    max_memberships = np.max(membership_matrix, axis=1)
    sum_memberships = np.sum(membership_matrix, axis=1)

    mpc = np.mean(max_memberships / sum_memberships)

    return mpc

#close to 0 values are better
#A value of 0 indicates a crisp or hard clustering, where data points have membership only to one cluster and there is no uncertainty
#higher values indicates uncertainty and fuzziness in the clustering, with data points having more equal memberships across multiple clusters.
def calculate_partition_entropy(membership_matrix):
    """
    Calculates the Partition Entropy for Fuzzy C-Means clustering.

    Parameters:
        membership_matrix (numpy.ndarray): Membership matrix of shape (n_samples, n_clusters).

    Returns:
        float: Partition Entropy value.
    """
    n_samples, n_clusters = membership_matrix.shape
    entropy = 0.0

    for i in range(n_samples):
        for j in range(n_clusters):
            if membership_matrix[i, j] > 0:
                entropy -= membership_matrix[i, j] * np.log2(membership_matrix[i, j])

    partition_entropy = entropy / n_samples

    return partition_entropy


"""## Em cada dataset execute o algoritmo FCM com a distância de City-Block 50 vezes para obter 
uma partição fuzzy em 7 grupos e selecione o melhor resultado segundo a função objetivo."""
def get_best_partition(data, n_clusters, m, distance_metric = 'cityblock', times_to_run=50):
    
    best_objective_value = 99999999999.9
    best_results = 0
    TIMES = times_to_run
    
    for i in range(TIMES):
    
      # Example usage
      #print("FCM: ", i + 1)
    
      centroids, membership_matrix, iterations = fuzzy_cmeans(data, n_clusters, m, distance_metric)
      objective_value = calculate_objective(data, centroids, membership_matrix, m, distance_metric)
      
      
      if(objective_value < best_objective_value):
        best_objective_value = objective_value
        best_results = centroids, membership_matrix, iterations
    
        #print("Centroids:")
        #print(centroids)
        #print("Membership matrix:")
        #print(membership_matrix)
        #print("Objective value:", objective_value)
        #print("Iterations:", iterations, "\n")
    
    #print(best_results, "\n", best_results.shape)
    #centroids, membership_matrix, iterations = best_results
    #return centroids, membership_matrix, iterations
    return best_results

def fuzzy_to_crisp_partition(membership_matrix):
    """
    Converts a fuzzy partition into a crisp partition.

    Parameters:
        membership_matrix (numpy.ndarray): Membership matrix of shape (n_samples, n_clusters).

    Returns:
        numpy.ndarray: Crisp partition of shape (n_samples,).
    """
    crisp_partition = np.argmax(membership_matrix, axis=1)

    return crisp_partition

#from [-1, 1]. -1 better
def calculate_ari(clustering_1, clustering_2):

  # Example clusterings
  #clustering1 = [0, 0, 1, 1, 2, 2]
  #clustering2 = [1, 1, 0, 0, 2, 2]

  # Calculate ARI
  ari = adjusted_rand_score(clustering_1, clustering_2)

  return ari

#from [0,1]. 1 is better
def calculate_f_measure(partition1, partition2):
    tp = sum(1 for i in partition1 for j in partition2 if i == j)  # Conta os verdadeiros positivos
    fp = len(partition1) - tp  # Calcula os falsos positivos
    fn = len(partition2) - tp  # Calcula os falsos negativos

    f_measure = (2 * tp) / (2 * tp + fp + fn)
    return f_measure

#from:
#https://pythonhosted.org/scikit-fuzzy/api/skfuzzy.cluster.html
def skfuzzy_fcm(data, n_clusters_c, m, distance_metric):


  data_city_block = cdist(data, data, metric='cityblock') #cityblock, euclidean, cosine

  # Set the random seed for numpy.random
  np.random.seed(RANDOM_SEED)

  # Perform Fuzzy C-means clustering
  # cntr, u, _, _, _, _, _ = fuzz.cluster.cmeans(
  cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
      data_city_block.T,
      n_clusters_c,
      m=2,
      error=0.005,
      maxiter=1000
  )

  # The 'u' matrix contains the fuzzy membership values for each data point
  return cntr, u, p

In [ ]:
"""
I. Considere os dados "Image Segmentation" do site uci machine learning
repository (https://archive.ics.uci.edu/ml/datasets/Image+Segmentation).

"""

NUMBER_OF_DATASETS = 3

PATH = 'https://raw.githubusercontent.com/allansdefreitas/unsupervised-learning/main/segmentation.data'
PATH2 = 'https://raw.githubusercontent.com/allansdefreitas/unsupervised-learning/main/segmentation.test'

dataset_original = pd.read_csv(PATH, sep=',')
dataset_original2 = pd.read_csv(PATH2, sep=',')

#concat datasets
frames = [dataset_original, dataset_original2]
dataset_original_indexes = pd.concat(frames)

dataset_original = dataset_original_indexes.reset_index(drop=True)

indexes = dataset_original_indexes.index

#obter os labels a priori
indexes = dataset_original_indexes.index
indexes_label = []

for i in indexes:
    indexes_label.append(i)

le = preprocessing.LabelEncoder()
labels_a_priori = le.fit_transform(indexes_label)


""" Considere 3 datasets: """
#o primeiro considerando as variáveis 4 a 9 (shape) ----------

dataset_1 = dataset_original.iloc[:,3:9]
#pre-processing of dataset
X_dataset_1 = preprocess_dataset(dataset_1)


#o segundo considerando as variaveis 10 a 19 (rgb) ----------
dataset_2 = dataset_original.iloc[:,9:19]
#pre-processing of dataset
X_dataset_2 = preprocess_dataset(dataset_2)

#O terceiro considerando as variaveis 4 a 19 (shape + rgb) -------
dataset_3 = dataset_original.iloc[:,3:19]
#pre-processing of dataset
X_dataset_3 = preprocess_dataset(dataset_3)


""" Em cada dataset execute o algoritmo FCM com a distância de City-Block
50 vezes para obter uma partição fuzzy em 7 grupos e selecione o melhor
resultado segundo a função objetivo. """

' Em cada dataset execute o algoritmo FCM com a distância de City-Block\n50 vezes para obter uma partição fuzzy em 7 grupos e selecione o melhor\nresultado segundo a função objetivo. '

In [ ]:
labels_a_priori, np.unique(labels_a_priori)

(array([0, 0, 0, ..., 1, 1, 1]), array([0, 1, 2, 3, 4, 5, 6]))

In [ ]:
#data = X_dataset_1
n_clusters = 7
m = 2 #{1.1; 1.6; 2.0}. 1.1 resuls on error: RuntimeWarning: overflow encountered in exp AND invalid value encountered in true_divide. USE OTHER IMPL OF FCM
distance_metric = 'cityblock'
best_objective_value = 99999999999.9
best_results = 0
times = 1 #50


datasets = [X_dataset_1, X_dataset_2, X_dataset_3]
best_results = []


for dataset_i in datasets:
  #print(dataset_i)
  centroids, U, iter = get_best_partition(dataset_i, n_clusters, m, distance_metric = 'cityblock', times_to_run=times)
  best_results.append([centroids, U, iter])


#Salvar melhores matrizes de grau de associação (U) como arquivos csv

#save datasets to csv files ---------------------##
for i in range(NUMBER_OF_DATASETS):
  membership_matrix = best_results[i][1] #i-th membership_matrix

  # save i-th dataset to csv file
  filename = 'dataset_'+ str(i + 1) + '_U_matrix'
  savetxt(filename + '.csv', membership_matrix, delimiter=',')

#load datasets from csv files --------------------##
membership_matrixes = []

for i in range(NUMBER_OF_DATASETS):

  # save i-th dataset to csv file
  filename = 'dataset_'+ str(i + 1) + '_U_matrix'
  membership_matrix = loadtxt(filename + '.csv', delimiter=',') #recover #i-th membership_matrix
  membership_matrixes.append(membership_matrix)

In [ ]:
type(datasets), len(datasets), type(datasets[0]), datasets[0].shape

(list, 3, numpy.ndarray, (2310, 6))

In [ ]:
type(membership_matrixes), len(membership_matrixes), membership_matrixes[0].shape

(list, 3, (2310, 7))

In [ ]:
membership_matrixes[0]

In [ ]:
"""Para cada dataset e partição fuzzy, calcule o Modified partition coefficient
e o Partition entropy. (OK. verificar) Comente"""

#Obtendo Modified partition coefficient e partition entropy para cada dataset

mpc_and_partition_entropies = []

for ith_mem_matrix in membership_matrixes:

  mpc = calculate_mpc(ith_mem_matrix)
  partition_entropy = calculate_partition_entropy(ith_mem_matrix)

  mpc_and_partition_entropies.append( [mpc, partition_entropy] )

In [ ]:
mpc_and_partition_entropies #It is CORRECT have values above 1 as partition entropy???

[[0.8668034002926496, 0.6009982633733827],
 [0.7557455813628058, 1.1225827976177263],
 [0.6112279719499126, 1.7032151086735674]]

In [ ]:
""" Para cada dataset e partição fuzzy, produza uma partição CRISP em 7
grupos e calcule o índice de Rand corrigido, e a F-measure (adaptada
para agrupamento). Comente """


#obtendo partiçoes CRISP
crisp_partitions = []

for i in range(NUMBER_OF_DATASETS):

  crisp = fuzzy_to_crisp_partition(membership_matrixes[i])
  crisp_partitions.append(crisp)


#Obtendo ARI

In [ ]:
crisp_partitions, crisp_partitions[0].shape, np.unique(crisp_partitions[0])

([array([1, 1, 1, ..., 1, 1, 3]),
  array([3, 3, 3, ..., 3, 3, 4]),
  array([1, 1, 1, ..., 1, 1, 2])],
 (2310,),
 array([0, 1, 2, 3, 4, 5, 6]))

In [ ]:
#test
e = 2001
sum = 0
for i in range(NUMBER_OF_DATASETS):

  sum += membership_matrixes[0][e][i]

sum

0.9752286022796354

In [ ]:
labels_a_priori.shape, crisp_partitions[0].shape

((2310,), (2310,))

In [ ]:
"""Para cada dataset e partição fuzzy, calcule o índice de Rand corrigido, 
e a F-measure (adaptada para agrupamento Comente"""

#Obtendo Índice de range corrigido e f-measure para cada partição CRISP

rand_index_f_measures = []

for ith_crisp_partition in crisp_partitions:

  clustering_rand_index = calculate_ari(ith_crisp_partition, labels_a_priori)
  f_measure = calculate_f_measure(ith_crisp_partition, labels_a_priori)

  rand_index_f_measures.append( [clustering_rand_index, f_measure] )

In [ ]:
rand_index_f_measures

[[0.024091342475916135, 0.30753021324004887],
 [0.4365846191519961, 0.525901566153829],
 [0.48124928664273703, 0.5634071389785168]]

In [ ]:
np.unique(crisp)

#entender via video aula etc sobre a aplicação do indice de rand corrigido e f-measure

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
!pip install scikit-fuzzy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 994.0/994.0 kB 31.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for scikit-fuzzy: filename=scikit_fuzzy-0.4.2-py3-none-any.whl size=894073 sha256=1d3a8777ecccc47c022b206314921d6996089695d177451af09e32c6c859c6fd
  Stored in directory: /root/.cache/pip/wheels/4f/86/1b/dfd97134a2c8313e519bcebd95d3fedc7be7944db022094bc8
Successfully built scikit-fuzzy


In [ ]:
import numpy as np
import skfuzzy as fuzz
from scipy.spatial.distance import cdist

# Generate some random data
data = np.random.rand(100, 2)

# Set the number of clusters
num_clusters = 3

# Apply city-block (Manhattan) distance effect
data_city_block = cdist(data, data, metric='cityblock') #euclidean, cosine

# Perform Fuzzy C-means clustering
cntr, u, _, _, _, _, _ = fuzz.cluster.cmeans(
    data_city_block.T,
    num_clusters,
    2,
    error=0.005,
    maxiter=1000
)

# The 'u' matrix contains the fuzzy membership values for each data point

# Print the cluster centers
print("Cluster centers:")
print(cntr)

# Print the fuzzy membership values for the first data point
print("Fuzzy membership values for data point 0:")
print(u[:, 0])


Cluster centers:
[[0.63426987 0.73273144 0.62516779 0.96392133 0.38844042 0.40026811
  0.82923236 0.73395712 0.81484214 0.386898   0.93211655 0.76215235
  0.40978678 0.40501087 0.43779735 0.30031976 0.5267397  1.11455595
  0.35638767 0.3186577  0.9196054  0.57313095 0.32201337 0.8438983
  0.54845586 0.75186943 0.3919268  0.76707401 0.72519528 0.68929161
  0.36657738 0.87095402 0.49092117 0.94300488 0.41678851 0.40957823
  0.88445394 0.62312635 0.65484623 0.38514636 0.46916258 0.99582991
  0.816051   0.72453609 0.85456775 0.98694773 1.02238191 0.89993047
  0.91114657 0.76810466 0.68931597 0.85992066 0.55263229 0.32320372
  0.45930787 0.72782545 0.37452632 0.32671074 0.85859556 0.4505577
  0.34621843 0.4673681  0.71206025 0.36029056 0.69485518 0.62161969
  0.59439387 0.88502077 0.63505368 0.54497058 0.89570662 0.2996956
  0.76931931 0.33204005 0.7549647  0.54058619 0.56029403 0.74121478
  1.23409149 0.93241322 0.37388046 0.62706068 0.81299254 0.94913901
  0.7864881  0.96185455 0.70750389

In [ ]:

import numpy as np
import skfuzzy as fuzz
from scipy.spatial.distance import cdist

# Set the random seed for reproducibility
RANDOM_SEED=42

np.random.seed(RANDOM_SEED)

# Generate some random data
data = np.random.rand(100, 2)

# Set the number of clusters
num_clusters = 3

# Apply city-block (Manhattan) distance effect
data_city_block = cdist(data, data, metric='cityblock') #cityblock, euclidean, cosine

# Set the random seed for numpy.random
np.random.seed(RANDOM_SEED)

# Perform Fuzzy C-means clustering
# cntr, u, _, _, _, _, _ = fuzz.cluster.cmeans(
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
    data_city_block.T,
    num_clusters,
    m=2,
    error=0.005,
    maxiter=1000
)

# The 'u' matrix contains the fuzzy membership values for each data point

return_func = cntr, u, p

# Print the cluster centers
print("Cluster centers:")
print(cntr)

# Print the fuzzy membership values for the first data point
print("Fuzzy membership values for data point 0:")
print(u[:, 0])



Cluster centers:
[[0.46274456 0.75777519 0.71170071 0.3173019  0.59533432 0.40334486
  1.17680507 0.69197533 0.43603768 0.73302008 1.03825065 0.56448648
  0.46288232 0.39714362 1.11227761 1.00410148 0.36134106 0.94340684
  0.82645236 0.82636793 0.39430948 0.35070899 0.33772505 0.44354712
  0.93513976 0.94497804 0.94836825 0.63863048 0.66927325 0.56273573
  0.71568179 1.0384653  0.41136274 0.28935776 0.39059057 1.13204627
  0.33643759 0.6914097  1.2528815  0.84243683 0.87098632 0.87662922
  0.61268292 0.73600093 0.99252549 0.28753253 0.80688579 0.861802
  0.68908145 0.78302805 0.33508691 0.45321262 1.21438925 0.42321912
  0.80971397 0.75573571 0.90786936 0.64468608 1.17377868 0.94699828
  0.82093661 0.82241337 0.47986967 0.81534662 0.4276768  0.78591828
  0.53380666 1.17974913 0.52215643 0.47166909 1.26593292 0.78099598
  0.87543229 0.70266024 0.60314948 1.22429512 0.40209831 1.29826657
  0.65826377 0.31517851 0.41513607 0.70221339 0.29649296 0.74974813
  0.35231497 1.22125121 0.8642175

In [ ]:
u.shape 

(3, 100)

In [ ]:
u

array([[0.75254085, 0.05736299, 0.16637424, 0.84119102, 0.2004429 ,
        0.71950683, 0.1203089 , 0.13376998, 0.40460008, 0.05467584,
        0.09568886, 0.1543952 , 0.50995925, 0.53999792, 0.1058772 ,
        0.09335675, 0.77302923, 0.16326376, 0.07120192, 0.10912383,
        0.61282596, 0.78300243, 0.73793073, 0.38761196, 0.0705007 ,
        0.14337184, 0.2039697 , 0.31915359, 0.23050239, 0.36244086,
        0.04152024, 0.08994081, 0.46966905, 0.94171726, 0.74780404,
        0.11826266, 0.84323755, 0.09783099, 0.13484961, 0.04213906,
        0.02923339, 0.07393312, 0.09864896, 0.05957111, 0.0489383 ,
        0.94856102, 0.04794493, 0.06096765, 0.15806333, 0.29055179,
        0.90431859, 0.36519349, 0.12080594, 0.58009687, 0.13290467,
        0.0568822 , 0.1477413 , 0.24367536, 0.12185575, 0.03398951,
        0.17418598, 0.0599141 , 0.3174435 , 0.15145045, 0.72914277,
        0.02911474, 0.3025998 , 0.10691741, 0.32601439, 0.76563723,
        0.1287745 , 0.07717251, 0.11385485, 0.15

In [ ]:
u_T = u.T
u_T.shape

(100, 3)

In [ ]:
u_T

array([[0.75254085, 0.14616545, 0.1012937 ],
       [0.05736299, 0.87568479, 0.06695222],
       [0.16637424, 0.09033586, 0.7432899 ],
       [0.84119102, 0.07890625, 0.07990272],
       [0.2004429 , 0.6526624 , 0.1468947 ],
       [0.71950683, 0.14194741, 0.13854576],
       [0.1203089 , 0.51042907, 0.36926203],
       [0.13376998, 0.07543418, 0.79079585],
       [0.40460008, 0.17346598, 0.42193394],
       [0.05467584, 0.06457528, 0.88074888],
       [0.09568886, 0.21428846, 0.69002269],
       [0.1543952 , 0.09301122, 0.75259358],
       [0.50995925, 0.31984802, 0.17019274],
       [0.53999792, 0.1286878 , 0.33131428],
       [0.1058772 , 0.20715438, 0.68696842],
       [0.09335675, 0.21246615, 0.69417711],
       [0.77302923, 0.1145783 , 0.11239247],
       [0.16326376, 0.71775516, 0.11898108],
       [0.07120192, 0.05527976, 0.87351832],
       [0.10912383, 0.63546666, 0.25540951],
       [0.61282596, 0.10814601, 0.27902804],
       [0.78300243, 0.10901808, 0.10797949],
       [0.

In [ ]:
u_T[0][0] + u_T[0][1] + u_T[0][2] 